name: ~ (iam) Install on Ubuntu

on:
  push:
    # paths:
      # - 'install'
      # - 'Brewfile'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repository
        uses: actions/checkout@v3
      - name: Get current working directory
        run: pwd
        id: pwd
      - name: test
        run: echo "Test"
      - name: Get PWD outputs
        run: echo "${{ join(steps.pwd.outputs.*, '\n') }}"
      - name: Install packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: git sudo software-properties-common python3-pip shellcheck lua-check
          version: 1.0
      - name: Execute ShellCheck
        run: test $(shellcheck -f gcc ./dot_zshrc ./dot_zshrc.d/* | grep -v "SC1036\|SC1056\|SC1070\|SC1072\|SC1073\|SC1083\|SC2034\|SC2139\|SC2148\|SC1090\|SC1117\|SC2206\|SC1009\|SC2016\|SC2046\|SC2154" | tee -a /dev/stderr | wc -l) -le 1
      # - name: Execute shellcheck(installer)
        # run: test $(git ls-files | grep "\.sh$" | xargs shellcheck -f gcc | grep -v "SC2086\|SC2046\|SC1090\|SC2034\|SC2005\|SC2154\|SC1091" | tee -a /dev/stderr | wc -l) -le 0
      # - name: Execute luacheck
        # run: luacheck -q .
